#!/bin/bash

if [[ "$1" == "-h" ]] || [[ $# -lt 1 ]]
then
    echo -e "Node information: \t\n kubeplugin nodes"
    echo -e "Pods information: \t\n kubeplugin pods <namespace>"
    echo -e "If you want use it as kubectl command run command: \n\n\t sudo cp kubeplugin /usr/bin/kubectl-kubeplugin \n\t kubectl kubeplugin -h"
    exit 0
fi

RESOURCE_TYPE=$1
NAMESPACE=$2

if [ "$RESOURCE_TYPE" = "node" ] || [ "$RESOURCE_TYPE" = "nodes" ]; then
    echo "$(kubectl top nodes)"
    exit 0
else
    printf "%-20s %-20s %-35s %-20s %-20s\n" "Resource" "Namespace" "Name" "CPU" "Memory"
fi
# Retrieve resource usage statistics from Kubernetes

kubectl top "$RESOURCE_TYPE" -n "$NAMESPACE" -A | tail -n +2 | while read -r line
 do
    read -r NS NAME CPU MEMORY <<< "$line"
    if [[ "$NS" == "$2" ]]; then 
        printf "%-20s %-20s %-35s %-20s %-20s\n" "$RESOURCE_TYPE" "$NS" "$NAME" "$CPU" "$MEMORY"
    fi

done